[package]
name = "decoreco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
colored = "2.0.0"
indicatif = "0.16.2"
prettytable-rs = "0.8.0"
tempfile = "3.2.0"
